<font size=\"12\" color=\"#bfffffff\"></font><font size=\"14\" color=\"#bfffffff\">Привет, $user<br> 
Хочу предложить вступить в наше объединение, мы играем в EVE online уже 15 лет.<br>У нас многоуровневая организация поэтому можно выбрать любую из 3х корпораций в зависимости от опыта игры и квалификации<br>
<br> Письмо написано именно тебе так  как ты находишься в НПЦ корпорации, а следовательно высокая вероятность, что ты захочешь к нам присоединиться, да и н</font><font size=\"14\" color=\"#ff00ff00\">алог у нас меньше 11%</font><font size=\"14\" color=\"#bfffffff\">). <br>
<br>Мы набираем людей с разным уровнем игры, требования для вступления минимальны и не потребуют от тебя ничего сверхъестественного: быть адекватным, не сквернословить и по возможности участвовать в общих движухах. 
<br>Наличие голосового чата дискорда на вылетах - обязательное условие. Общение в голосе - это единственный способ, максимальной и полноценной коммуникации в игре.<br>
<br>Для развития нам нужны новые игроки, которые помогут нам удержать и расширить территории которые мы уже имеем, а мы в свою очередь предоставим все возможности для интересной совместной игры и хорошего заработка (</font><font size=\"14\" color=\"#ff00ff00\"> майнерам на коветорах около 100 млн в час, агентранерам и плексранерам в районе 200 млн в час. при условии наличия омега статуса, альфа клоны зарабатывают раза в 4-5 меньше).</font>
<font size=\"14\" color=\"#bfffffff\"> У нас нет никаких скрытых сборов и комиссий , а те налоги которые мы собираем(5-7%) идут на содержание инфраструктуры и </font><font size=\"14\" color=\"#ff00ff00\">выплату компенсаций(до 75% стоимости корабля)</font><font size=\"14\" color=\"#bfffffff\"> при сливах на боевых вылетах. <br>
<br></font><font size=\"14\" color=\"#ff00ffff\"><b>Те кто только начал играть(или проживает в империи) - можно вступить в корпорацию -  </font><font size=\"14\" color=\"#ffd98d00\"><loc><a href=\"showinfo:2//98399497\">Red Cold Chili Banderlogs Academy</a></loc><br><br></font><font size=\"14\" color=\"#ff00ffff\">Для тех кто хочет попробовать пожить в нулях в регионе </font><font size=\"14\" color=\"#ffd98d00\"><a href=\"showinfo:3//10000023\">Pure Blind</a></font><font size=\"14\" color=\"#ff00ffff\"> в домашней системе  </font><font size=\"14\" color=\"#ffd98d00\"><a href=\"showinfo:5//30002005\">5ZXX-K</a></font>
<font size=\"14\" color=\"#ff00ffff\"> <loc> (есть клайм, нпц агенты </font><font size=\"14\" color=\"#ffd98d00\"><a href=\"showinfo:30//500016\">Servant Sisters of EVE</a></font><font size=\"14\" color=\"#ff00ffff\"> = </font><font size=\"14\" color=\"#ffd98d00\"><a href=\"showinfo:33469\">Astero Blueprint</a></font><font size=\"14\" color=\"#ff00ffff\">  и  </loc></font><font size=\"14\" color=\"#ffd98d00\"><a href=\"showinfo:30//500018\">Mordu's Legion Command</a></font><font size=\"14\" color=\"#ff00ffff\"> = </font><font size=\"14\" color=\"#ffd98d00\"><a href=\"showinfo:33817\">Garmur Blueprint</a></font><font size=\"14\" color=\"#ff00ffff\">  <loc>) </loc> -  </font><font size=\"14\" color=\"#ffd98d00\"><loc><a href=\"showinfo:2//98520878\">Russian Space Community</a></loc>
<br><br></font><font size=\"14\" color=\"#ff00ffff\">И для опытных пвп пилотов    </font><font size=\"14\" color=\"#ffd98d00\"><loc><a href=\"showinfo:2//604035876\">Free Space Tech</a></loc></b>
<br><br></font><font size=\"14\" color=\"#bfffffff\">Вступление в </font><font size=\"14\" color=\"#ffd98d00\"><loc><a href=\"showinfo:2//98399497\">Red Cold Chili Banderlogs Academy</a></loc></font><font size=\"14\" color=\"#bfffffff\"> свободное. Нужно Кликнуть на название корпорации </font><font size=\"14\" color=\"#ffd98d00\"><loc><a href=\"showinfo:2//98399497\">Red Cold Chili Banderlogs Academy</a></loc></font><font size=\"14\" color=\"#bfffffff\"> снизу будет кнопка - Подать заявку.
<br>После подачи заявку проверяйте статус приглашения в разделе \"Корпорация -&gt; Вербовка -&gt; Мои заявки\"<br><br>Вступить в </font><font size=\"14\" color=\"#ffd98d00\"><loc><a href=\"showinfo:2//98520878\">Russian Space Community</a></loc></font><font size=\"14\" color=\"#bfffffff\"> или </font><font size=\"14\" color=\"#ffd98d00\"><loc><a href=\"showinfo:2//604035876\">Free Space Tech</a></loc></font><font size=\"14\" color=\"#bfffffff\"> можно после собеседования в дискорде в ходе которого будет понятен уровень игры. <br>Нужно будет зайти в рекрутскую, рассказать в какую из корпораций вы хотите вступить и ответить на простые вопросы.
<br><br>На все вопросы могу ответить в </font><font size=\"14\" color=\"#ffffe400\"><a href=\"https://discord.gg/xNhme66\">Дискорде</a></font><font size=\"14\" color=\"#bfffffff\"> или в дискорде в личку Lapsh banderlog#7317</font>